### ISSUE TITLE
hello thanks for sharing the code.

### ISSUE THREAD

**Issue by webesistemas** [climberdigital/docker-php-local-multiversion#1]
when I access a .php file I get the error 500
you know what it can be?

error log 

2023/02/14 03:42:55 [error] 39#39: *7 no host in upstream ":9000", client: 172.22.0.1, server: local.teste.com, request: "GET / HTTP/1.1", host: "local.teste.com"

**Comment by climberdigital** [comment]
Hi! Not really sure, but it seems like nginx can't connect to your PHP container, for some reason. It's hard to debug this way as you might have overriden the default settings with anything you wanted, so I just don't know your entire configuration.

I'm fairly certain, though, that the PHP environment is functioning when you follow the setup instructions on the main page of this repository, and copy the default settings and substitute them with your nginx virtual host config and domain/php version pairs. Tested it on Laravel and Wordpress without issues.

Make sure that all the containers are running, then, if you make changes to the docker-compose or nginx config, stop them, and rebuild them.

**Comment by webesistemas** [comment]
I'll review all the steps and see if I missed anything, thanks

**Comment by webesistemas** [comment]
it worked correctly thank you very much
